/**
 * Simulation events.
 */

const EventType = Object.freeze({
  MISSION_CREATED: "MISSION_CREATED",
  MISSION_ARRIVED: "MISSION_ARRIVED",

  MISSION_PLANNING_STARTED: "MISSION_PLANNING_STARTED",
  MISSION_PLANNING_COMPLETED: "MISSION_PLANNING_COMPLETED",

  BRIEFING_STARTED: "BRIEFING_STARTED",
  BRIEFING_COMPLETED: "BRIEFING_COMPLETED",

  AIRCRAFT_PREPARATION_STARTED: "AIRCRAFT_PREPARATION_STARTED",
  AIRCRAFT_PREPARATION_COMPLETED: "AIRCRAFT_PREPARATION_COMPLETED",

  TAKEOFF: "TAKEOFF",

  AIR_MISSION_STARTED: "AIR_MISSION_STARTED",
  AIR_MISSION_COMPLETED: "AIR_MISSION_COMPLETED",

  LANDING: "LANDING",

  DEBRIEFING_STARTED: "DEBRIEFING_STARTED",
  DEBRIEFING_COMPLETED: "DEBRIEFING_COMPLETED",

  MAINTENANCE_STARTED: "MAINTENANCE_STARTED",
  MAINTENANCE_COMPLETED: "MAINTENANCE_COMPLETED",

  PILOT_REST_COMPLETED: "PILOT_REST_COMPLETED",
  SCHEDULER_RETRY: "SCHEDULER_RETRY",

  GROUND_ABORT: "GROUND_ABORT",
  AIR_ABORT: "AIR_ABORT",
  WEATHER_ABORT: "WEATHER_ABORT",

  SORTIE_COMPLETED: "SORTIE_COMPLETED",
});

module.exports = EventType;
