export const defaultScenario = {
  mission: {
    missionCount: 18,
    simulationDurationHours: 8,
    primaryMissionType: "combat_air_patrol",
    missionPriority: "high",
    randomScheduling: true,
    allowMissionOverlap: false,
    minimumPreparationTimeMinutes: 30,
    missionDurationEstimateMinutes: 90,
  },

  aircraft: {
    totalAircraft: 16,
    aircraftType: "f16",
    availableAircraft: 14,
    unavailableAircraft: 2,
    maintenanceImpact: true,
    maintenanceDurationMinutes: 120,
    turnaroundTimeMinutes: 45,
    aircraftFailureRate: 5,
  },

  pilots: {
    totalPilots: 24,
    availablePilots: 22,
    averagePilotRating: "experienced",
    missionQualification: "all",
    pilotFatigue: true,
    restTimeMinutes: 90,
    maxSortiesPerPilot: 2,
    maxFlightHoursPerPilot: 6,
  },

  groundCrew: {
    totalTeams: 6,
    availableTeams: 5,
    aircraftPreparedPerTeam: 1,
    averagePreparationTimeMinutes: 35,
    maintenanceAssignment: true,
    maintenanceCrewAllocationPercent: 30,
    shiftModel: "two_shift",
    crewRestTimeMinutes: 60,
  },

  runways: {
    totalRunways: 2,
    operationalRunways: 2,
    takeoffsPerHour: 20,
    landingsPerHour: 20,
    runwayMaintenance: false,
    temporaryClosure: false,
    schedulingStrategy: "fifo",
    minimumSeparationMinutes: 3,
  },

  environment: {
    weatherCondition: "clear",
    weatherSeverityPercent: 20,
    visibilityRangeKm: 10,
    lowVisibilityOperations: false,
    windSpeedKnots: 12,
    crosswindLimitKnots: 25,
    timeOfDay: "day",
    nightOperationPenalty: false,
  },

  scheduling: {
    missionSchedulingStrategy: "priority_based",
    dynamicRescheduling: false,
    distributionMode: "even",
    minimumGapMinutes: 10,
    prioritizeCriticalMissions: true,
    priorityBoostFactor: 2,
    delayPolicy: "wait",
    maxAllowedDelayMinutes: 60,
  },

  rules: {
    groundAbortLogic: true,
    airAbortLogic: true,
    maxAbortProbabilityPercent: 15,
    allocationStrategy: "balanced",
    preventOverallocation: true,
    retryFailedMissions: false,
    maxRetryAttempts: 2,
    emergencyMissions: false,
    priorityOverride: false,
  },

  missionMix: {
    combatAirPatrolPercent: 35,
    strikePercent: 25,
    interceptPercent: 20,
    reconnaissancePercent: 10,
    trainingPercent: 10,
    supportMissions: false,
    supportMissionType: "standby",
    complexityLevel: "medium",
    mixedMissionPackages: false,
    highPrioritySharePercent: 30,
    criticalMissionInjection: false,
  },

  constraints: {
    availableFuelUnits: 10000,
    averageFuelPerMission: 450,
    availableWeaponPackages: 40,
    weaponAllocationPolicy: "priority_based",
    sparePartsStock: 80,
    limitMaintenanceBySpareParts: true,
    constraintEnforcement: "strict",
    resourceOverrideForCriticalMissions: false,
  },
};
