import { useMemo, useState } from "react";
import {
  MdAssignment,
  MdCheckCircle,
  MdCancel,
  MdSchedule,
  MdPlayCircle,
  MdHelp,
} from "react-icons/md";

import Badge from "../common/Badge";
import Card from "../common/Card";
import EmptyState from "../common/EmptyState";
import SectionHeader from "../common/SectionHeader";
import Table from "../common/Table";
import Modal from "../common/Modal";

import MissionToolbar from "./MissionToolbar";

function MissionTable({ result }) {
  const missions = result?.missions || [];

  const [searchTerm, setSearchTerm] = useState("");
  const [activeFilter, setActiveFilter] = useState("All");
  const [selectedMission, setSelectedMission] = useState(null);

  const [sortConfig, setSortConfig] = useState({
    key: "scheduledStartTime",
    direction: "asc",
  });

  function handleSort(key) {
    setSortConfig((current) => {
      if (current.key === key) {
        return {
          key,
          direction: current.direction === "asc" ? "desc" : "asc",
        };
      }

      return {
        key,
        direction: "asc",
      };
    });
  }

  const filteredMissions = useMemo(() => {
    const filtered = missions.filter((mission) => {
      const search = searchTerm.toLowerCase();

      const matchesSearch =
        mission.id?.toLowerCase().includes(search) ||
        mission.name?.toLowerCase().includes(search) ||
        mission.aircraftIds?.[0]?.toLowerCase().includes(search) ||
        mission.pilotIds?.[0]?.toLowerCase().includes(search);

      const matchesFilter =
        activeFilter === "All" ||
        mission.status?.toLowerCase() === activeFilter.toLowerCase();

      return matchesSearch && matchesFilter;
    });

    return [...filtered].sort((a, b) => {
      const aValue = a[sortConfig.key];
      const bValue = b[sortConfig.key];

      if (aValue === null || aValue === undefined) return 1;
      if (bValue === null || bValue === undefined) return -1;

      if (aValue < bValue) {
        return sortConfig.direction === "asc" ? -1 : 1;
      }

      if (aValue > bValue) {
        return sortConfig.direction === "asc" ? 1 : -1;
      }

      return 0;
    });
  }, [missions, searchTerm, activeFilter, sortConfig]);

  const missionStats = {
    total: missions.length,
    completed: missions.filter((mission) => mission.status === "COMPLETED")
      .length,
    aborted: missions.filter((mission) => mission.status === "ABORTED").length,
    filtered: filteredMissions.length,
  };

  const columns = [
    { key: "id", label: "Mission", sortable: true },
    { key: "status", label: "Status", sortable: true },
    { key: "aircraft", label: "Aircraft" },
    { key: "pilot", label: "Pilot" },
    { key: "scheduledStartTime", label: "Scheduled", sortable: true },
    { key: "actualStartTime", label: "Start", sortable: true },
    { key: "endTime", label: "End", sortable: true },
    { key: "abort", label: "Abort Reason" },
  ];

  return (
    <section className="space-y-6">
      <SectionHeader
        eyebrow="Operations"
        title="Mission Operations"
        subtitle="Detailed mission-level execution data generated by the sortie simulation."
        icon={<MdAssignment />}
      />

      {missions.length === 0 ? (
        <EmptyState
          title="No missions generated yet"
          message="Run the simulation to view mission assignments and execution details."
          icon={<MdAssignment />}
        />
      ) : (
        <Card>
          <MissionStatsBar stats={missionStats} />

          <MissionToolbar
            searchTerm={searchTerm}
            onSearchChange={setSearchTerm}
            activeFilter={activeFilter}
            onFilterChange={setActiveFilter}
          />

          <div className="mt-6">
            {filteredMissions.length === 0 ? (
              <EmptyState
                title="No matching missions"
                message="Try changing the search term or status filter."
              />
            ) : (
              <Table
                columns={columns}
                sortConfig={sortConfig}
                onSort={handleSort}
              >
                {filteredMissions.map((mission) => (
                  <MissionRow
                    key={mission.id}
                    mission={mission}
                    onClick={() => setSelectedMission(mission)}
                  />
                ))}
              </Table>
            )}
          </div>
        </Card>
      )}

      <MissionDetailsModal
        mission={selectedMission}
        onClose={() => setSelectedMission(null)}
      />
    </section>
  );
}

function MissionStatsBar({ stats }) {
  return (
    <div className="mb-6 grid gap-3 md:grid-cols-4">
      <MiniStat label="Total" value={stats.total} />
      <MiniStat label="Completed" value={stats.completed} tone="success" />
      <MiniStat label="Aborted" value={stats.aborted} tone="danger" />
      <MiniStat label="Filtered" value={stats.filtered} tone="primary" />
    </div>
  );
}

function MiniStat({ label, value, tone = "neutral" }) {
  const tones = {
    neutral: "text-slate-300",
    success: "text-emerald-400",
    danger: "text-red-400",
    primary: "text-sky-400",
  };

  return (
    <div className="rounded-xl border border-slate-800 bg-slate-950/60 px-4 py-3">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
        {label}
      </p>

      <p className={`mt-1 text-2xl font-bold ${tones[tone]}`}>{value}</p>
    </div>
  );
}

function MissionRow({ mission, onClick }) {
  return (
    <tr
      onClick={onClick}
      className="cursor-pointer transition hover:bg-slate-800/40"
    >
      <td className="px-5 py-4">
        <div>
          <p className="font-semibold text-white">{mission.id}</p>
          <p className="text-sm text-slate-500">{mission.name}</p>
        </div>
      </td>

      <td className="px-5 py-4">
        <MissionStatusBadge status={mission.status} />
      </td>

      <td className="px-5 py-4 text-sm text-slate-300">
        {mission.aircraftIds?.[0] || "—"}
      </td>

      <td className="px-5 py-4 text-sm text-slate-300">
        {mission.pilotIds?.[0] || "—"}
      </td>

      <td className="px-5 py-4 text-sm text-slate-300">
        {formatTime(mission.scheduledStartTime)}
      </td>

      <td className="px-5 py-4 text-sm text-slate-300">
        {formatTime(mission.actualStartTime)}
      </td>

      <td className="px-5 py-4 text-sm text-slate-300">
        {formatTime(mission.endTime)}
      </td>

      <td className="px-5 py-4 text-sm text-slate-400">
        {mission.abortReason || "—"}
      </td>
    </tr>
  );
}

function MissionDetailsModal({ mission, onClose }) {
  if (!mission) return null;

  return (
    <Modal
      isOpen={Boolean(mission)}
      title={mission.id}
      subtitle={mission.name}
      onClose={onClose}
    >
      <div className="mb-5">
        <MissionStatusBadge status={mission.status} />
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <DetailItem label="Aircraft" value={mission.aircraftIds?.[0] || "—"} />
        <DetailItem label="Pilot" value={mission.pilotIds?.[0] || "—"} />
        <DetailItem
          label="Ground Crew"
          value={mission.groundCrewIds?.join(", ") || "—"}
        />
        <DetailItem label="Runway" value={mission.runwayId || "—"} />
        <DetailItem
          label="Scheduled Start"
          value={formatTime(mission.scheduledStartTime)}
        />
        <DetailItem
          label="Actual Start"
          value={formatTime(mission.actualStartTime)}
        />
        <DetailItem label="End Time" value={formatTime(mission.endTime)} />
        <DetailItem
          label="Abort Reason"
          value={mission.abortReason || "—"}
          full
        />
      </div>
    </Modal>
  );
}

function DetailItem({ label, value, full = false }) {
  return (
    <div
      className={`rounded-xl border border-slate-800 bg-slate-950/60 p-4 ${
        full ? "md:col-span-2" : ""
      }`}
    >
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
        {label}
      </p>

      <p className="mt-2 text-sm font-semibold text-white">{value}</p>
    </div>
  );
}

function MissionStatusBadge({ status }) {
  const normalizedStatus = status || "UNKNOWN";

  const config = {
    COMPLETED: {
      variant: "success",
      icon: <MdCheckCircle />,
    },
    ABORTED: {
      variant: "danger",
      icon: <MdCancel />,
    },
    READY: {
      variant: "warning",
      icon: <MdSchedule />,
    },
    PLANNED: {
      variant: "primary",
      icon: <MdSchedule />,
    },
    IN_PROGRESS: {
      variant: "warning",
      icon: <MdPlayCircle />,
    },
    UNKNOWN: {
      variant: "neutral",
      icon: <MdHelp />,
    },
  };

  const selected = config[normalizedStatus] || config.UNKNOWN;

  return (
    <Badge variant={selected.variant} icon={selected.icon}>
      {normalizedStatus.replaceAll("_", " ")}
    </Badge>
  );
}

function formatTime(minutes) {
  if (minutes === null || minutes === undefined) {
    return "—";
  }

  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;

  return `${String(hours).padStart(2, "0")}:${String(mins).padStart(2, "0")}`;
}

export default MissionTable;
