import Card from "../common/Card";

function formatTime(value) {
  if (value === undefined || value === null) return "-";

  const mins = Math.round(Number(value));
  const h = Math.floor(mins / 60);
  const m = mins % 60;

  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}

function formatDuration(value) {
  if (value === undefined || value === null) return "-";
  return `${value} min`;
}

function badge(successful) {
  if (successful) {
    return "bg-green-500/10 text-green-300 border-green-500/40";
  }

  return "bg-red-500/10 text-red-300 border-red-500/40";
}

export default function SortieTable({ sorties = [] }) {
  const sortedSorties = [...sorties].sort((a, b) => {
    return (a.takeoffTime ?? 0) - (b.takeoffTime ?? 0);
  });

  return (
    <Card>
      <div className="mb-6">
        <p className="text-xs uppercase tracking-[0.25em] text-green-400">
          Sorties
        </p>

        <h3 className="mt-1 text-lg font-semibold text-slate-100">
          Sortie Execution Log
        </h3>

        <p className="mt-1 text-sm text-slate-500">
          Actual flight execution records generated by the backend.
        </p>
      </div>

      {sortedSorties.length === 0 ? (
        <div className="rounded-xl border border-dashed border-green-900/40 p-8 text-center">
          <p className="text-slate-400">
            Backend did not return any sortie records.
          </p>

          <p className="mt-2 text-xs text-slate-500">
            This section will populate when missions successfully take off and
            land.
          </p>
        </div>
      ) : (
        <div className="overflow-auto">
          <table className="w-full min-w-[1200px] text-sm">
            <thead className="border-b border-green-900/40 text-slate-400">
              <tr>
                <th className="px-3 py-3 text-left">Sortie</th>
                <th className="px-3 py-3 text-left">Mission</th>
                <th className="px-3 py-3 text-left">Type</th>
                <th className="px-3 py-3 text-left">Priority</th>
                <th className="px-3 py-3 text-left">Aircraft</th>
                <th className="px-3 py-3 text-left">Pilot</th>
                <th className="px-3 py-3 text-left">Req. Rating</th>
                <th className="px-3 py-3 text-left">Takeoff</th>
                <th className="px-3 py-3 text-left">Landing</th>
                <th className="px-3 py-3 text-left">Planned</th>
                <th className="px-3 py-3 text-left">Actual</th>
                <th className="px-3 py-3 text-left">Status</th>
              </tr>
            </thead>

            <tbody>
              {sortedSorties.map((sortie) => (
                <tr
                  key={sortie.id}
                  className="border-b border-green-900/20 text-slate-300"
                >
                  <td className="px-3 py-3">
                    <div>
                      <p className="font-medium text-slate-100">{sortie.id}</p>
                      <p className="text-xs text-slate-500">
                        {sortie.missionId}
                      </p>
                    </div>
                  </td>

                  <td className="px-3 py-3">
                    {sortie.missionName || sortie.missionId || "-"}
                  </td>

                  <td className="px-3 py-3">{sortie.missionType || "-"}</td>

                  <td className="px-3 py-3">{sortie.priority || "-"}</td>

                  <td className="px-3 py-3">{sortie.aircraftId || "-"}</td>

                  <td className="px-3 py-3">{sortie.pilotId || "-"}</td>

                  <td className="px-3 py-3">
                    {sortie.requiredPilotRating || "-"}
                  </td>

                  <td className="px-3 py-3">
                    {formatTime(sortie.takeoffTime)}
                  </td>

                  <td className="px-3 py-3">
                    {formatTime(sortie.landingTime)}
                  </td>

                  <td className="px-3 py-3">
                    {formatDuration(sortie.plannedDuration)}
                  </td>

                  <td className="px-3 py-3">
                    {formatDuration(sortie.actualDuration)}
                  </td>

                  <td className="px-3 py-3">
                    <span
                      className={`rounded-full border px-3 py-1 text-xs font-semibold ${badge(
                        sortie.successful,
                      )}`}
                    >
                      {sortie.successful ? "SUCCESS" : "FAILED"}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Card>
  );
}
